site_name: My Austrian German
extra:
  cite:
    swick_grammar_drills: >-
      Swick, Ed.
      [_German Grammar Drills._](https://www.amazon.com/dp/1264286104/)
      Premium 4th Edition.
      McGraw Hill, 2022.
    wolf_sog_amoi: >-
      Wolf, Manfred.
      [_Sog amoi: Das etwas andere Mundartwörterbuch für Oberösterreich._](https://www.amazon.com/dp/3991132281)
      1. Auflage.
      TRAUNER Verlag + Buchservice GmbH, 2021.
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  # enable footnotes https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes
  # enable annotations https://squidfunk.github.io/mkdocs-material/reference/annotations/
  - attr_list
  - md_in_html
  - pymdownx.superfences
  # enable admonitions https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # enable content tabs https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # enable tooltips https://squidfunk.github.io/mkdocs-material/reference/tooltips/
  - abbr
  - attr_list
  - pymdownx.snippets
  # enable formatting https://squidfunk.github.io/mkdocs-material/reference/formatting/
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # enable diagrams https://squidfunk.github.io/mkdocs-material/reference/diagrams/
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - macros
  - privacy
  - search:
      lang: [de, en]
theme:
  name: material
  icon:
    annotation: material/arrow-right-circle
